version: ~> 1.0

language: nix

os:
  - linux
  - osx

dist: xenial

cache:
  directories:
    - "/nix/store"
    - "$HOME/.cabal/store"
  timeout: 600

before_install:
  - nix-shell --pure --run true

install:
  - nix-shell --pure --run 'cabal v2-update'

script:
  - nix-shell --pure --run 'make test'
  - nix-shell --pure --run 'make lint'

before_deploy:
  - nix-shell --pure --run 'make out/build/release/smoke'
  - mkdir -p out/publish
  - cp out/build/release/smoke "out/publish/smoke-${TRAVIS_TAG}-$(uname -s)-$(uname -m)"

deploy:
  provider: releases
  edge: true
  on:
    tags: true
  draft: true
  file_glob: true
  file: "out/publish/*"
  overwrite: true
  cleanup: false
  token:
    secure: "dt3YESE3S86tqhWu0J8HxTTsTewcj6S3o//P9hwlFAcPUsqzlZLL9KmySnYvNQ91TuBpUu2blXVRY+CFPU59MEIXtSI4ZSHWEd9vetMdW7GcoN8HYNQapL0jEvIx1D2495jCWr6gEHERFUr6eJgI0ZasmlIPSPL5H3vFS2SxGRs="
