os:
  - linux
  - osx

sudo: false

language: generic

cache:
  directories:
    - "$HOME/.stack"
    - ".stack-work/tools"
  timeout: 600

addons:
  apt:
    packages:
      - libgmp-dev
      - libssl-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - |
    if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then
      travis_retry curl -sSL 'https://www.stackage.org/stack/osx-x86_64' | tar xz --strip-components=1 -C ~/.local/bin '*/stack'
    elif [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then
      travis_retry curl -sSL 'https://www.stackage.org/stack/linux-x86_64' | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
  - stack setup

install:
  - stack --no-terminal install --only-dependencies

script:
  - make test
  - |
    if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then
      make lint
    fi

before_deploy:
  - make out/build/release/smoke
  - mkdir -p out/publish
  - cp out/build/release/smoke "out/publish/smoke-${TRAVIS_TAG}-$(uname -s)-$(uname -m)"

deploy:
  provider: releases
  draft: true
  file_glob: true
  file: out/publish/*
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: "dt3YESE3S86tqhWu0J8HxTTsTewcj6S3o//P9hwlFAcPUsqzlZLL9KmySnYvNQ91TuBpUu2blXVRY+CFPU59MEIXtSI4ZSHWEd9vetMdW7GcoN8HYNQapL0jEvIx1D2495jCWr6gEHERFUr6eJgI0ZasmlIPSPL5H3vFS2SxGRs="
